#ifndef H_0_DEFINES
#define H_0_DEFINES

#define SENSOR_RAINDROP D5
#define SENSOR_PHOTO D6
#define SENSOR_DHT D7
#define SENSOR_WINDOW_TEMPERATURE D8

#define OUTPUT_GORDEN D2
#define OUTPUT_WINDOW D3
#define OUTPUT_DEFOGGER D4

#define WIFI_SSID "Hayo lo"
#define WIFI_PASSWORD ""

#define THINGSPEAK_WRITE_API_KEY "NGY3LJQSU36OQ58F"
#define THINGSPEAK_READ_API_KEY "0KLXCZUCGDSPHAIK"
#define THINGSPEAK_CHANNEL_ID 1983297

#define THINGSPEAK_FIELD_IS_AUTO 1
#define THINGSPEAK_FIELD_WINDOW_STATUS 2
#define THINGSPEAK_FIELD_CURTAIN_STATUS 3
#define THINGSPEAK_FIELD_DEFOGGER_STATUS 4

#endif
